---
language: ruby
bundler_args: "--without system"
script: "bundle exec rspec --color --format documentation spec/unit"
notifications:
  email: false
sudo: false
rvm:
  - "2.4.0"
  - "2.3.0"
  - "2.2.4"
  - "2.1.8"
  - "2.0.0"
  - "jruby-19mode"
jdk:
    - oraclejdk8
